// =============================================================================
// ChatAssistant — grounded, per-case Q&A.
//
// Everything the model says is marked with the violet AI accent (flat, never a
// gradient) so an analyst can never mistake it for system data. When the
// assistant declines to answer from data it doesn't have, that turn gets a
// distinct, reassuring treatment — a trust signal, not an error.
// =============================================================================

import React, { useEffect, useRef, useState } from 'react';
import type { ChatMessage } from '../lib/types';
import { Send, ShieldCheck, Sparkle } from './icons';

const REFUSAL_RX =
	/\b(i (don'?t|do not) have|isn'?t (in|part of)|not (available|included|in scope|in the case)|no (record|history|log|correspondence|contact)\b.*(provided|in the case|available)|outside (the )?scope|can'?t (provide|confirm) .*(don'?t have|not have))/i;

const isRefusal = (text: string): boolean => REFUSAL_RX.test(text);

export interface ChatAssistantProps {
	messages: ChatMessage[];
	onSend?: (text: string) => void;
	busy?: boolean;
	/** disables the composer with an explanatory note (e.g. sample case) */
	disabledReason?: string;
}

export const ChatAssistant: React.FC<ChatAssistantProps> = ({ messages, onSend, busy, disabledReason }) => {
	const [draft, setDraft] = useState('');
	const scrollRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		const el = scrollRef.current;
		if (el) el.scrollTop = el.scrollHeight;
	}, [messages.length, busy]);

	const submit = (): void => {
		const text = draft.trim();
		if (!text || busy || disabledReason || !onSend) return;
		onSend(text);
		setDraft('');
	};

	return (
		<div className="overflow-hidden rounded-card border border-line bg-surface" style={{ borderLeft: '3px solid #8B5CF6' }}>
			<div className="flex items-center gap-2 border-b border-line px-4 py-3">
				<span className="grid h-6 w-6 place-items-center rounded" style={{ color: '#8B5CF6', background: 'rgba(139,92,246,0.14)' }}>
					<Sparkle size={14} />
				</span>
				<span className="text-[13px] font-semibold text-ink">Case assistant</span>
				<span className="rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider" style={{ color: '#8B5CF6', background: 'rgba(139,92,246,0.14)' }}>
					AI-generated
				</span>
			</div>

			<p className="border-b border-line px-4 py-2 text-[11px] leading-relaxed text-ink-faint">
				Answers are generated by an AI model grounded only in this case’s data — the vendor master record, extracted
				invoice fields, rules, risk signals, and any verification result.
			</p>

			<div ref={scrollRef} className="pfs-scroll max-h-[340px] space-y-3 overflow-y-auto px-4 py-4">
				{messages.length === 0 && (
					<p className="text-[12.5px] text-ink-faint">
						No questions yet. Ask why this case was routed the way it was, what a specific flag means, or what the
						verification found.
					</p>
				)}

				{messages.map((m, i) => {
					if (m.role === 'reviewer') {
						return (
							<div key={i} className="flex justify-end">
								<div className="max-w-[85%] rounded-lg rounded-br-sm border border-line bg-surface-2 px-3 py-2 text-[12.5px] leading-relaxed text-ink">
									{m.text}
								</div>
							</div>
						);
					}
					const refusal = isRefusal(m.text);
					return (
						<div key={i} className="flex flex-col gap-1">
							<div className="flex items-center gap-1.5">
								<span className="rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider" style={{ color: '#8B5CF6', background: 'rgba(139,92,246,0.14)' }}>
									AI
								</span>
								{refusal && (
									<span className="inline-flex items-center gap-1 text-[10px] font-medium uppercase tracking-wide text-ink-faint">
										<span style={{ color: '#8B5CF6' }}>
											<ShieldCheck size={11} />
										</span>
										declined — data not in case
									</span>
								)}
							</div>
							<div
								className="max-w-[92%] rounded-lg rounded-bl-sm border px-3 py-2 text-[12.5px] leading-relaxed text-ink"
								style={
									refusal
										? { borderColor: 'rgba(139,92,246,0.4)', background: 'rgba(139,92,246,0.08)' }
										: { borderColor: '#334155', background: '#1B2130', borderLeft: '2px solid #8B5CF6' }
								}
							>
								{m.text}
								{refusal && (
									<p className="mt-1.5 border-t border-[rgba(139,92,246,0.25)] pt-1.5 text-[11px] italic text-ink-dim">
										Expected behaviour: the assistant won’t fabricate data it wasn’t given.
									</p>
								)}
							</div>
						</div>
					);
				})}

				{busy && (
					<div className="flex items-center gap-1.5 text-[12px] text-ink-faint">
						<span className="h-1.5 w-1.5 animate-pulse rounded-full bg-violet" />
						assistant is thinking…
					</div>
				)}
			</div>

			<div className="border-t border-line px-3 py-3">
				{disabledReason ? (
					<p className="px-1 py-2 text-[11.5px] italic text-ink-faint">{disabledReason}</p>
				) : (
					<div className="flex items-end gap-2">
						<textarea
							value={draft}
							onChange={(e) => setDraft(e.target.value)}
							onKeyDown={(e) => {
								if (e.key === 'Enter' && !e.shiftKey) {
									e.preventDefault();
									submit();
								}
							}}
							rows={1}
							placeholder="Ask about this case…"
							className="pfs-scroll max-h-28 min-h-[38px] flex-1 resize-none rounded-md border border-line bg-surface-2 px-3 py-2 text-[12.5px] text-ink placeholder:text-ink-faint focus:border-violet"
						/>
						<button
							type="button"
							onClick={submit}
							disabled={!draft.trim() || busy}
							className="pfs-press inline-flex h-[38px] cursor-pointer items-center gap-1.5 rounded-md px-3 text-[12.5px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"
							style={{ background: '#8B5CF6' }}
						>
							<Send size={14} />
							Ask
						</button>
					</div>
				)}
			</div>
		</div>
	);
};
