// =============================================================================
// VerificationView — the simulated out-of-band vendor call.
//
// Trust rule: the transcript is AI-generated and NO real call was placed. That
// must be unmissable *everywhere it appears* — a header banner, a per-turn
// origin, and, critically, baked into any copied / exported text so the
// disclaimer travels with the content.
// =============================================================================

import React, { useCallback, useRef, useState } from 'react';
import type { VerificationResult } from '../lib/types';
import { Check, ChevronDown, ChevronRight, Copy, Phone, Sparkle } from './icons';

const SIM_TAG = '[SIMULATED VERIFICATION — AI-GENERATED, NOT A REAL PHONE CALL]';

export function buildTranscriptText(r: VerificationResult): string {
	const lines: string[] = [
		SIM_TAG,
		'This transcript was generated by an AI model to stand in for a future telephony integration.',
		'No call was placed. Do not treat any statement below as a real vendor confirmation.',
		'',
		`Invoice: ${r.invoice_number ?? '—'}`,
		`Outcome: ${r.verification.toUpperCase()}`,
		r.completed_at ? `Generated: ${r.completed_at}` : '',
		'',
		'--- QUESTIONS ---',
		...r.questions.map((q, i) => `${i + 1}. ${q}`),
		'',
		'--- SIMULATED CALL ---',
		...r.transcript.map((t) => `${t.speaker === 'sentinel' ? 'SENTINEL (AI)' : 'VENDOR (AI, simulated)'}: ${t.text}`),
		'',
		'--- ASSESSMENT NOTES (AI-generated) ---',
		r.notes,
		'',
		SIM_TAG,
	];
	return lines.filter((l) => l !== undefined).join('\n');
}

const OUTCOME: Record<VerificationResult['verification'], { label: string; fg: string; tint: string }> = {
	confirmed: { label: 'Confirmed', fg: '#9AA7B8', tint: 'rgba(154,167,184,0.14)' },
	suspicious: { label: 'Suspicious — do not pay', fg: '#F5B942', tint: 'rgba(245,158,11,0.16)' },
};

export const VerificationView: React.FC<{ result: VerificationResult }> = ({ result }) => {
	const [notesOpen, setNotesOpen] = useState(false);
	const [copied, setCopied] = useState(false);
	const timer = useRef<number | undefined>(undefined);
	const outcome = OUTCOME[result.verification];

	const copy = useCallback(async () => {
		try {
			await navigator.clipboard.writeText(buildTranscriptText(result));
			setCopied(true);
			window.clearTimeout(timer.current);
			timer.current = window.setTimeout(() => setCopied(false), 1600);
		} catch {
			/* clipboard blocked — no-op */
		}
	}, [result]);

	return (
		<div className="overflow-hidden rounded-card border border-line bg-surface" style={{ borderLeft: '3px solid #8B5CF6' }}>
			{/* header: dual origin markers, always visible */}
			<div className="flex flex-wrap items-center gap-2 border-b border-line px-4 py-3">
				<span className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-ink">
					<Phone size={14} className="text-ink-dim" />
					Vendor verification call
				</span>
				<span
					className="inline-flex items-center gap-1.5 rounded px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider"
					style={{ color: '#F5B942', background: 'rgba(245,158,11,0.16)' }}
				>
					Simulated · no call placed
				</span>
				<span
					className="inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider"
					style={{ color: '#8B5CF6', background: 'rgba(139,92,246,0.14)' }}
				>
					<Sparkle size={11} />
					AI-generated
				</span>
				<span
					className="ml-auto inline-flex items-center gap-1.5 rounded px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide"
					style={{ color: outcome.fg, background: outcome.tint }}
				>
					{outcome.label}
				</span>
			</div>

			<div className="space-y-4 px-4 py-4">
				<p className="rounded-md border border-line bg-surface-2 px-3 py-2 text-[12px] leading-relaxed text-ink-dim">
					This transcript was produced by an AI model as a placeholder for a future telephony / voice integration.
					<strong className="text-ink"> No phone call took place.</strong> Every line — including the vendor’s — is
					model-generated and must not be relied on as a real vendor confirmation.
				</p>

				{/* questions */}
				<div>
					<h4 className="mb-1.5 text-[11px] font-semibold uppercase tracking-[0.14em] text-ink-dim">
						Verification questions
					</h4>
					<ol className="space-y-1.5">
						{result.questions.map((q, i) => (
							<li key={i} className="flex gap-2 text-[12.5px] leading-relaxed text-ink-dim">
								<span className="mt-0.5 font-mono text-[11px] text-ink-faint">{String(i + 1).padStart(2, '0')}</span>
								<span>{q}</span>
							</li>
						))}
					</ol>
				</div>

				{/* transcript */}
				<div>
					<div className="mb-1.5 flex items-center justify-between">
						<h4 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-ink-dim">Simulated call</h4>
						<button
							type="button"
							onClick={copy}
							className="pfs-press inline-flex cursor-pointer items-center gap-1.5 rounded border border-line bg-surface px-2 py-1 text-[11px] font-medium text-ink-dim hover:border-ink-dim hover:text-ink"
						>
							{copied ? <Check size={12} strokeWidth={2.5} /> : <Copy size={12} />}
							{copied ? 'Copied with disclaimer' : 'Copy transcript'}
						</button>
					</div>
					<ol className="space-y-2">
						{result.transcript.map((t, i) => {
							const sentinel = t.speaker === 'sentinel';
							return (
								<li
									key={i}
									className="rounded-md border border-line p-3"
									style={{ background: sentinel ? 'rgba(139,92,246,0.06)' : '#1B2130' }}
								>
									<div className="mb-1 flex items-center gap-2">
										<span className="text-[11px] font-semibold uppercase tracking-wide" style={{ color: sentinel ? '#A78BFA' : '#9AA7B8' }}>
											{sentinel ? 'Sentinel' : 'Vendor'}
										</span>
										<span className="text-[10px] uppercase tracking-wide text-ink-faint">
											{sentinel ? 'AI agent' : 'AI, simulated'}
										</span>
									</div>
									<p className="text-[12.5px] leading-relaxed text-ink">{t.text}</p>
								</li>
							);
						})}
					</ol>
				</div>

				{/* notes */}
				<div className="rounded-md border border-line bg-surface-2">
					<button
						type="button"
						onClick={() => setNotesOpen((v) => !v)}
						aria-expanded={notesOpen}
						className="flex w-full cursor-pointer items-center gap-2 px-3 py-2 text-left text-[12px] font-semibold uppercase tracking-wide text-ink-dim hover:text-ink"
					>
						{notesOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
						Assessment notes
						<span className="ml-1 rounded px-1.5 py-0.5 text-[10px] font-bold tracking-wider" style={{ color: '#8B5CF6', background: 'rgba(139,92,246,0.14)' }}>
							AI
						</span>
					</button>
					<div className="pfs-expand" data-open={notesOpen}>
						<div className="pfs-expand-inner">
							<p className="border-t border-line px-3 py-3 text-[12.5px] leading-relaxed text-ink-dim">{result.notes}</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};
